http:
  routers:
    backend:
      entryPoints:
        - web
      rule: "PathPrefix(`/api`)"
      priority: 2
      service: backend
    frontend:
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      priority: 1
      service: frontend
  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend-green:8080"
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend-green:80"
